### ISSUE TITLE
incremental development, week 2, Sunday Roll Call

### ISSUE THREAD

**Issue by Atinos31** [HackYourFutureBelgium/class-11-12#43]
## Roll call .
🤨🛒👩🏽‍💻🚶🏽‍♀️🛀🏽🚴🏽‍♀️💅🏽✍🏽🥱🙂
1. this week was kinda tough... i did not do all that was required, study-wise...i hope to catch up soon.

**Comment by sharafcs50** [comment]
1. Hi, went well. Looking forward to next week. The ice-breaker was good.

**Comment by krakla** [comment]
🤒🍗📚🖥😱😏🥴🧐🏃🏽‍♂️📖😴

**Comment by samirm00** [comment]
:smiley: Hey

**Comment by iLienstAr** [comment]
Hey @Atinos31 you opened your own Roll Call.
It brings up the idea of letting a student start Roll Call, thanks for that!

But, until now, it is the coach who opens the Roll Call, so you should comment on this one, instead of opening one yourself ;) 

https://github.com/HackYourFutureBelgium/class-11-12/issues/42

**Comment by Atinos31** [comment]
@iLienstAr  I am actually still figuring these things out😉

**Comment by iLienstAr** [comment]
@Atinos31 you are doing well!

**Comment by lauraramirez220612** [comment]
Hi,
